name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vtarginoo
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push Image
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --build-arg SPRING_APPLICATION_NAME=mvp-luke-law \
            --build-arg SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} \
            --build-arg TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
            --build-arg TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
            --build-arg TWILIO_WHATSAPP_FROM=${{ secrets.TWILIO_WHATSAPP_FROM }} \
            -f Dockerfile  # Specify the path to your Dockerfile if it's not in the root
            -t vtarginoo/lukelawapi:latest \
            .


